<a href="https://colab.research.google.com/github/jmaydwell1/Tensorflow-Deep-Learning/blob/main/00_tensorflow_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
 ones = tf.ones(shape=(5, 300))

In [9]:
zeros = tf.zeros(shape=(5, 300))

In [10]:
ones * zeros

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [11]:
tf.multiply(ones, zeros)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [12]:
zeros_reshaped = tf.reshape(zeros, shape=(300, 5))

In [13]:
ones @ zeros_reshaped

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [14]:
tf.transpose(ones)

<tf.Tensor: shape=(300, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       ...,
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [15]:
tf.matmul(tf.transpose(ones), zeros)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [16]:
tf.tensordot(tf.transpose(ones), zeros, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [17]:
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.uniform((224, 224, 3), minval=0, maxval=1)
random_tensor 

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7493447 , 0.73561966, 0.45230794],
        [0.49039817, 0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718, 0.63932586],
        ...,
        [0.8035464 , 0.8265822 , 0.84540355],
        [0.16108847, 0.48667014, 0.6170937 ],
        [0.22355545, 0.93454087, 0.5319209 ]],

       [[0.7508148 , 0.46019256, 0.14229465],
        [0.10500956, 0.72874916, 0.89662087],
        [0.85220826, 0.76973283, 0.11408448],
        ...,
        [0.38387823, 0.72712064, 0.7561674 ],
        [0.70352066, 0.22680473, 0.24423313],
        [0.39240444, 0.32533252, 0.39407527]],

       [[0.74291146, 0.54543686, 0.32094967],
        [0.6671035 , 0.8900143 , 0.64271927],
        [0.5317905 , 0.21345353, 0.71189904],
        ...,
        [0.53968227, 0.7233304 , 0.7900686 ],
        [0.99334645, 0.857829  , 0.67977047],
        [0.8087704 , 0.06597769, 0.62171316]],

       ...,

       [[0.84861326, 0.6271888 , 0.7023717 ],
        [0.46

In [18]:
min = tf.reduce_min(random_tensor, axis=1)
max = tf.reduce_max(random_tensor, axis=1)
min, max

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[4.81557846e-03, 3.61919403e-04, 1.04762316e-02],
        [1.57868862e-03, 7.04526901e-03, 3.81457806e-03],
        [2.68554688e-03, 6.20603561e-04, 4.91738319e-04],
        [3.47518921e-03, 3.78012657e-04, 1.62353516e-02],
        [4.99725342e-04, 7.01427460e-04, 1.23119354e-03],
        [5.62739372e-03, 5.28657436e-03, 1.62795782e-02],
        [8.92996788e-04, 4.01687622e-03, 4.61709499e-03],
        [1.32584572e-03, 2.43222713e-03, 4.57584858e-03],
        [1.82788372e-02, 1.36065483e-03, 6.10423088e-03],
        [1.60312653e-03, 2.27320194e-03, 3.61275673e-03],
        [8.34465027e-04, 1.54817104e-03, 3.53908539e-03],
        [4.17864323e-03, 1.55812502e-02, 1.33935213e-02],
        [1.18041039e-03, 1.20317936e-03, 1.62267685e-03],
        [8.37624073e-03, 3.30805779e-04, 1.95264816e-04],
        [5.01728058e-03, 5.37216663e-03, 8.28146935e-03],
        [7.46309757e-03, 1.33943558e-03, 9.07468796e-03],
        [2.31814384e-

In [24]:
import numpy as np
G = tf.constant(np.random.randint(0,100), shape=(1,224,224,3))
G

<tf.Tensor: shape=(1, 224, 224, 3), dtype=int32, numpy=
array([[[[76, 76, 76],
         [76, 76, 76],
         [76, 76, 76],
         ...,
         [76, 76, 76],
         [76, 76, 76],
         [76, 76, 76]],

        [[76, 76, 76],
         [76, 76, 76],
         [76, 76, 76],
         ...,
         [76, 76, 76],
         [76, 76, 76],
         [76, 76, 76]],

        [[76, 76, 76],
         [76, 76, 76],
         [76, 76, 76],
         ...,
         [76, 76, 76],
         [76, 76, 76],
         [76, 76, 76]],

        ...,

        [[76, 76, 76],
         [76, 76, 76],
         [76, 76, 76],
         ...,
         [76, 76, 76],
         [76, 76, 76],
         [76, 76, 76]],

        [[76, 76, 76],
         [76, 76, 76],
         [76, 76, 76],
         ...,
         [76, 76, 76],
         [76, 76, 76],
         [76, 76, 76]],

        [[76, 76, 76],
         [76, 76, 76],
         [76, 76, 76],
         ...,
         [76, 76, 76],
         [76, 76, 76],
         [76, 76, 76]]]], dtype

In [25]:
G_squeezed = tf.squeeze(G)
G_squeezed 

<tf.Tensor: shape=(224, 224, 3), dtype=int32, numpy=
array([[[76, 76, 76],
        [76, 76, 76],
        [76, 76, 76],
        ...,
        [76, 76, 76],
        [76, 76, 76],
        [76, 76, 76]],

       [[76, 76, 76],
        [76, 76, 76],
        [76, 76, 76],
        ...,
        [76, 76, 76],
        [76, 76, 76],
        [76, 76, 76]],

       [[76, 76, 76],
        [76, 76, 76],
        [76, 76, 76],
        ...,
        [76, 76, 76],
        [76, 76, 76],
        [76, 76, 76]],

       ...,

       [[76, 76, 76],
        [76, 76, 76],
        [76, 76, 76],
        ...,
        [76, 76, 76],
        [76, 76, 76],
        [76, 76, 76]],

       [[76, 76, 76],
        [76, 76, 76],
        [76, 76, 76],
        ...,
        [76, 76, 76],
        [76, 76, 76],
        [76, 76, 76]],

       [[76, 76, 76],
        [76, 76, 76],
        [76, 76, 76],
        ...,
        [76, 76, 76],
        [76, 76, 76],
        [76, 76, 76]]], dtype=int32)>

In [31]:
tensor = tf.constant(np.random.randint(0,10,10), shape=(1,1,1,1,10))
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 10), dtype=int64, numpy=array([[[[[9, 5, 4, 2, 4, 1, 1, 7, 6, 7]]]]])>

In [32]:
tensor_squeezed = tf.squeeze(tensor)
tensor_squeezed 

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([9, 5, 4, 2, 4, 1, 1, 7, 6, 7])>

In [34]:
max = tf.argmax(tensor_squeezed).numpy()
max

0

In [35]:
hot_encoding = tf.one_hot(tensor_squeezed, depth=4)
hot_encoding

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>